[tool.poetry]
name = "toradh"
version = "0.1.0"
description = ""
authors = ["Santiago Bassani <santiago.bassani96@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
typeguard = "^4.3.0"


[tool.poetry.group.dev.dependencies]
mypy = "^1.10.1"
ruff = "^0.5.1"


[tool.poetry.group.test.dependencies]
pytest = "^8.2.2"
mockito = "^1.5.0"
pytest-cov = "^5.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
